version: 0.0
os: linux
files:
  - source: /static/
    destination: /home/webadmin/sites/bertieblackman.co.uk/html
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root